Automate array booking in
moka-guys/moka-fe pull request #670
Opened 2021-06-22 10:19 UTC by ErinPeat

- Create script to automatically book in patients/ array tests from txt files exported from GW
- Create config script 
- Create Form in Moka to auto book in and for users to continue booking patients in manually (s0202_AutoBookingInArrays & s0202_AutoBookingInArrays_SQL)
- Add a button to the 0101 Add array request form to enable users to s0202_AutoBookingInArrays

2021-06-23 16:19 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 0 of 6 files reviewed, 9 unresolved discussions (waiting on @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 89 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbjR_Dt7kno-jSi_p:-MctbjR_Dt7kno-jSi_q:b-yz0jo1) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L89)):*
> ```
> patient_error
> ```
what is this? not in docstring
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 89 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbmaWC0kuyk-q5XqJ:-MctbmaWC0kuyk-q5XqK:bqbm6n0) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L89)):*
> ```
> i
> ```
not informative name
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 97 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbrTe4D_wc9oNbJcx:-MctbrTe4D_wc9oNbJcy:b-ppmx5e) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L97)):*
> ```
> # 
> ```
not sure if you're following a style guide but could you put comments on their own line (above the line that it's describing) - this is a example where it's a weird place, mid query
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 114 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctcQqP304ErtTe9OnE:-MctcQqP304ErtTe9OnF:b-6jw87s) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L114)):*
> ```
> else:·
> ```
could this be elif to avoid nested if's?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 118 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mctcas_8y39Z2sIzWS9:-Mctcas_8y39Z2sIzWSA:b-6kvebc) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L118)):*
> ```Python
>                 message = "Success"
>                 df.loc[i,'Patient_Moka_status'] = message # Add status to df for logging 
>             else:  # Patient is not in Moka, to insert 
> ```

un-nest as above
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 119 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctdI3U2hSKkUwsaslr:-MctdI3U2hSKkUwsasls:b4sdu8c) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L119)):*
> ```
> ather information for insert
> ```
read GW to get info to insert into Moka
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 423 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctVJ2n-9RSMKXLJ3IB:-MctVJ2n-9RSMKXLJ3IC:b-no9bto) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L423)):*
> ```Python
>             df['Gender'] = df['Gender'].replace(['Female','Male'],['F','M'])    # Change to match Patients table in Moka
>             if 'Processed_status' not in df.columns:
>                 df['Processed_status'] = 0 # Add column to df
> ```

Assume this populate all rows with 0?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 427 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbcDm-Fvst9KzAGHC:-MctbcDm-Fvst9KzAGHD:b-f4xgdc) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L427)):*
> ```Python
>             for i in range(len(df)): # Create a loop to go through the df
>                 if df.loc[i,'Processed_status'] == 0:  # Don't re run a row that's already been processed        
>                     patient_error_status, df = import_check_patients_table_moka(False, i) # Attempt to book Patient into Moka
> ```

what is the input False?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 427 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-McteoJo0rXGJxnqk4zX:-McteoJp8LCYdh3z-lIF:bw2xeva) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L427)):*
> ```Python
>             for i in range(len(df)): # Create a loop to go through the df
>                 if df.loc[i,'Processed_status'] == 0:  # Don't re run a row that's already been processed        
>                     patient_error_status, df = import_check_patients_table_moka(False, i) # Attempt to book Patient into Moka
> ```

progress marker - I got up to here


<!-- Sent from Reviewable.io -->

2021-06-25 11:41 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 0 of 6 files reviewed, 35 unresolved discussions (waiting on @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 134 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1uqst6jo_-0EHQOIS:-Md1uqst6jo_-0EHQOIT:beeo3sc) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L134)):*
> ```
> ····················
> ```
white space
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 160 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1v8JO-1cPrSuYKMUM:-Md1v8JO-1cPrSuYKMUN:bnm99oc) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L160)):*
> ```
> nternal_ID_return
> ```
can we do a check we've got the right ID before we use it?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 181 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1vG6v3bq6CtSLkOOp:-Md1vG6v3bq6CtSLkOOq:b7flcyd) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L181)):*
> ```Python
>                     #print(sql_check_patient) # DEBUG PATIENT
>                     sql_check_patient_return = mc.fetchall(sql_check_patient) 
>                     if len(sql_check_patient_return) == 1: # If this returns 1, the patient has been added successfully 
> ```

can we check the details/content of the test line up with what's expected
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 206 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u3vY9hxdjx69VxOe:-Md1u3vY9hxdjx69VxOf:b-c787z1) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L206)):*
> ```
> i
> ```
input is i but df is returned? sorry if i missed it but where is df created or why is it returned? 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 208 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1pYWL581nK1JckqAh:-Md1pYWM0jc117DtjWGj:bq2jkgy) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L208)):*
> ```Python
> def import_check_array_table_moka(test_error, i):
>     '''
>     This function checks if there is a test in the ArrayTest table for the Patient.
> ```

in a docstring for a function I also like to state what the expected inputs are and what it returns
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 212 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1pgcS4DH0s1sXVAyp:-Md1pgcS4DH0s1sXVAyq:b-iit9qi) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L212)):*
> ```Python
>     If there is a test and it has any other status (which means it's ongoing), nothing is done
>     '''
>     try:
> ```

can we move the comment to describe why a try except statement is needed to here
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 247 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1sHmUDiw0Mc8f4C6Q:-Md1sHmV9y04haFlwP-F:b-so310b) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L247)):*
> ```Python
>             )
>             #print(sql_get_check1ID) # DEBUG TEST
>             date_to_squish = sql_ArrayTest_insert_return[0][2]
> ```

sql_arrayTest_insert_return returns results of a query in a list of tuples, where the tuple contains (internalpatientid,specimenid,created date)
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 256 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1ri4B1j0xbd4_Zy4_:-Md1ri4B1j0xbd4_Zy4a:b-so310b) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L256)):*
> ```Python
>                                         " '{Requested_date}',  '{Booked_in_by}')" 
>             ).format(
>                 Patient_ID = sql_ArrayTest_insert_return[0][0], # The query returns a tuple, within a list
> ```

sql_arrayTest_insert_return returns results of a query in a list of tuples, where the tuple contains (internalpatientid,specimenid,created date)
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 262 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1sQmT1IefPsYQ4foW:-Md1sQmT1IefPsYQ4foX:bjdndy7) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L262)):*
> ```Python
>                 Requested_date = adjusted_referall_date, 
>                 Staff_PC = computer_name,
>                 Booked_in_by = sql_get_check1ID_return[0][0]
> ```

sql_get_check1id contains a list of tuples, where the tuple contains a single entry - (check1id)
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 287 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1tK_QB--nThteJ-7D:-Md1tK_QB--nThteJ-7E:bc3qbuv) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L287)):*
> ```
> sql_check_arraytest_return_after_insert
> ```
variable name is quite similar to the sql query run - this is good but could there be a standardised way, eg one suffixed with _sql and the results  suffixed with _results?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 295 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1ssG62Ai5n618f9oR:-Md1ssG62Ai5n618f9oS:b-b0ix9y) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L295)):*
> ```Python
>                 df.loc[i,'Booking_in_sample_status'] = 'Failed'   
>                 test_error = True
>             else:
> ```

at this point can we check some info in from the array test from the arraytestid returned with what is expected, eg spec number and internal patient id? (eg change sql_check_arraytest_after_insert
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 332 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u92i-R0VqfeE4P80:-Md1u92i-R0VqfeE4P81:b-e04pn3) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L332)):*
> ```
> df
> ```
as above, I don't know where this is created
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 340 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1xjcN5eeQ9g_z_TIt:-Md1xjcN5eeQ9g_z_TIu:b-jok6hm) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L340)):*
> ```Python
> def save_move_txt(df, error_occurred):
>     '''
>     Save the df to the same txt file 
> ```

describe inputs?
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 343 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1x1dk86EfHvKeGGUZ:-Md1x1dk86EfHvKeGGU_:boaumc2) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L343)):*
> ```
> to_process_path
> ```
may be overkill but could this be given as an input - not sure if having a global variable that is changed as we loop through the files could introduce an issue
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 345 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1xOX82QaCzrjFcovR:-Md1xOX82QaCzrjFcovS:bo3xi5u) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77 [...]

2021-06-25 11:53 UTC, aledj2 requested changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 1 of 6 files reviewed, 42 unresolved discussions (waiting on @ErinPeat)

___
*[forms/0101 Add array request, line 1 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md2-Khr1JiSK7z-0jIa:-Md2-Khr1JiSK7z-0jIb:b-t7ja0m) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0101 Add array request#L1)):*
> ```
> Option Compare Database
> ```

is this a new form or a copy/modification of an existing one?
___
*[forms/0101 Add array request, line 18 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1z8Lb2gGhqDdOb_Jb:-Md1z8Lb2gGhqDdOb_Jc:bvsqwyu) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0101 Add array request#L18)):*
> ```
> cWhite = RGB(255, 255, 255)
> 
> If (IsNull(Me.Sex) Or Me.Sex = "U") And IsNull(Me.Sexed) Then
> ```

comments?
___
*[forms/0101 Add array request, line 161 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1zb8i83KpfuDWAZug:-Md1zb8i83KpfuDWAZuh:b3kre) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0101 Add array request#L161)):*
> ```
>     
> End Sub
> ST
> ```

?
___
*[forms/0202 AutoBookingInArrays, line 15 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md2-YGt1tRFNMvoQdEH:-Md2-YGt1tRFNMvoQdEI:b-xbkir3) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L15)):*
> ```
> 'set path to python script
> 'BookingInPath = """\\gstt.local\Apps\Moka\Files\Software\ImportTxtToDB.py"""
> BookingInPath = """\\gstt.local\shared\Genetics_Data2\Moka_dev\erin_dev\auto_booking_array_test\ImportTxtToDB.py"""
> ```

needs changing before release
___
*[forms/0202 AutoBookingInArrays, line 21 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md205jN6mmOkLx69NyP:-Md205jN6mmOkLx69NyQ:b-671tib) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L21)):*
> ```
> 
> If MsgBox("Have you closed the txt file you'd like to book in?", vbYesNoCancel, "Txt file closed?") _
>     = vbYes Then
> ```

can this be added to line above (even if a bit long - personally I prefer that to make it more readable)
___
*[forms/0202 AutoBookingInArrays, line 53 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md201Ju0RVpNRDSXCUy:-Md201Ju0RVpNRDSXCUz:bv9oryi) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L53)):*
> ```
>     
> 
>     Else
> ```

unindent
___
*[forms/0202 AutoBookingInArrays, line 55 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md204-JEXINSfwlMwuh:-Md204-JEXINSfwlMwui:bxtaw95) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L55)):*
> ```
>     Else
>     MsgBox " Please close the txt file before clicking the button again", , "Close txt file"
>     End If
> ```

decrease indent


<!-- Sent from Reviewable.io -->

2021-06-25 11:54 UTC, aledj2 reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 2 of 6 files reviewed, 42 unresolved discussions (waiting on @ErinPeat)



<!-- Sent from Reviewable.io -->

2021-06-30 10:41 UTC, ErinPeat reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 2 of 6 files reviewed, 42 unresolved discussions (waiting on @aledj2 and @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 89 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbjR_Dt7kno-jSi_p:-MdLgclf98oqZZoSmIuR:bb6ia9w) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L89)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> patient_error
> ```
what is this? not in docstring
</blockquote></details>

Explanation added to doc string. 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 89 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbmaWC0kuyk-q5XqJ:-MdLh3mYCRlVmt8xGINC:bf4l3kf) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L89)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> i
> ```
not informative name
</blockquote></details>

Changed to df_row 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 97 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctbrTe4D_wc9oNbJcx:-MdMIbH-Bu2Vm43iyPuO:bxngx85) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L97)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> # 
> ```
not sure if you're following a style guide but could you put comments on their own line (above the line that it's describing) - this is a example where it's a weird place, mid query
</blockquote></details>

All comments moved as requested
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 114 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctcQqP304ErtTe9OnE:-MdMMlew8ndNHlQ_AF3m:b-hn0dpb) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L114)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> else:·
> ```
could this be elif to avoid nested if's?
</blockquote></details>

Updated to elif 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 118 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mctcas_8y39Z2sIzWS9:-MdMMnd--mLUL5p_FAu4:b-plconw) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L118)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

un-nest as above
</blockquote></details>

as above, updated to elif 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 119 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MctdI3U2hSKkUwsaslr:-MdMLitS3-fGzLNQA1C2:bir0ajo) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L119)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> ather information for insert
> ```
read GW to get info to insert into Moka
</blockquote></details>

Comment added 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 134 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1uqst6jo_-0EHQOIS:-MdMLqZ8Cai6dY46fPyl:ba3dfob) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L134)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> ····················
> ```
white space
</blockquote></details>

Removed
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 160 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1v8JO-1cPrSuYKMUM:-MdMlMLi20DMD8lTJH4i:b9fg7mj) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L160)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> nternal_ID_return
> ```
can we do a check we've got the right ID before we use it?
</blockquote></details>

Extra SQL added where the patient first and last name from the txt file, along with the PatientTrustID from GW (returned on line 160) are all part of the WHERE clause to ensure this is the right ID for the patient
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 181 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1vG6v3bq6CtSLkOOp:-MdMm60_9OaejW9qiwhC:bcg0l0h) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L181)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we check the details/content of the test line up with what's expected
</blockquote></details>

There's a check on line 203? Is that sufficient? 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 206 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u3vY9hxdjx69VxOe:-MdMmGV87sOGFhCsiDWs:b-rqasot) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L206)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> i
> ```
input is i but df is returned? sorry if i missed it but where is df created or why is it returned? 
</blockquote></details>

The df is created on line 489 when the txt file is imported. Returning the rows alone causes a lot of formatting issues with the df (e.g. all the column entries are used as headers) and these then need to be pivoted etc and then concatenated back together. I experimented with that option for a while but returning the entire df and just editing a row of it at a time with the functions was the easiest way to keep it all together. The input is currently the index of the current row of the df that is being looped through
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 208 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1pYWL581nK1JckqAh:-MdMo6d7AspuX3TP0Vwj:b-bw8e1h) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L208)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

in a docstring for a function I also like to state what the expected inputs are and what it returns
</blockquote></details>

Updated!
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 212 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1pgcS4DH0s1sXVAyp:-MdMoQUSDKcdZGd1Y_aS:b41jbgn) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L212)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can we move the comment to describe why a try except statement is needed to here
</blockquote></details>

I'm not sure there is one at the moment? Have added though !
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 247 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1sHmUDiw0Mc8f4C6Q:-MdMpGb_6DaEU53OCn3r:bqmjwcm) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L247)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sql_arrayTest_insert_return returns results of a query in a list of tuples, where the tuple contains (internalpatientid,specimenid,created date)
</blockquote></details>

Added!
___
*[code/automat [...]

2021-07-02 15:48 UTC, aledj2 requested changes
> Reviewed 1 of 6 files at r1, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 181 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1vG6v3bq6CtSLkOOp:-MdbmnwI6_CZWiaaUGT2:b-x41ggr) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L181)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

There's a check on line 203? Is that sufficient? 
</blockquote></details>

The GW test is good. And this test is also ok, but I'd like to test the internal patient id returned from `select @@identity` is correct - can we include that in the where clause?

Can this also happen before the patient log is updated
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 206 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u3vY9hxdjx69VxOe:-Mdbndnj4kK9cKDE-clM:b-ap3br1) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L206)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

The df is created on line 489 when the txt file is imported. Returning the rows alone causes a lot of formatting issues with the df (e.g. all the column entries are used as headers) and these then need to be pivoted etc and then concatenated back together. I experimented with that option for a while but returning the entire df and just editing a row of it at a time with the functions was the easiest way to keep it all together. The input is currently the index of the current row of the df that is being looped through
</blockquote></details>

if you are updating what is a global variable (df) it doesn't need to be returned as it doesn't exist solely in this object. similarly I still don't see the need for the test error to be imported if the value of test error is not used, but only set. it doesn't need to be imported in order for it to be returned. I don't think this breaks anything though...
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 332 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u92i-R0VqfeE4P80:-MdbrLSc9MLID_Sx4Sl9:bzbbgkp) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L332)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> df
> ```
as above, I don't know where this is created
</blockquote></details>

As df isn't created within this function I don't think it needs to be returned, but it obviously isn't breaking anything... maybe I have misunderstood!
___
*[forms/0101 Add array request, line 18 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1z8Lb2gGhqDdOb_Jb:-MdbtgLy9M_DP_Jkk6mS:bojx8x1) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0101 Add array request#L18)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

I can add if you like but this isn't code I wrote?
</blockquote></details>

if it hasn't been changed I'll let you off! next time it might be good to add the form before you changed it and then add a commit with your changes to see what is new


<!-- Sent from Reviewable.io -->

2021-07-06 11:18 UTC, ErinPeat reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @aledj2 and @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 181 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1vG6v3bq6CtSLkOOp:-MdpcafR1ieHJW-EXG_u:bf9l94i) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L181)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

The GW test is good. And this test is also ok, but I'd like to test the internal patient id returned from `select @@identity` is correct - can we include that in the where clause?

Can this also happen before the patient log is updated
</blockquote></details>

Result of the select @@identity now in WHERE clause and entire check moved to have before PATIENT insert added to patient log 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 206 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u3vY9hxdjx69VxOe:-MdvSMNcCKhwD_q5uMqM:bxza88n) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L206)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if you are updating what is a global variable (df) it doesn't need to be returned as it doesn't exist solely in this object. similarly I still don't see the need for the test error to be imported if the value of test error is not used, but only set. it doesn't need to be imported in order for it to be returned. I don't think this breaks anything though...
</blockquote></details>

Updated to remove all returns and inputs which are global variables and added declaring them as global variables in the instances they are used 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 332 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1u92i-R0VqfeE4P80:-MdvSZkG8JFjXkRZjnOG:b-e3663x) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/code/automate_array_booking_in/ImportTxtToDB.py#L332)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

As df isn't created within this function I don't think it needs to be returned, but it obviously isn't breaking anything... maybe I have misunderstood!
</blockquote></details>

As above, removed, no longer returned
___
*[forms/0101 Add array request, line 18 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md1z8Lb2gGhqDdOb_Jb:-Mduq79RD3OtwUbT0T2J:bfla802) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0101 Add array request#L18)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

if it hasn't been changed I'll let you off! next time it might be good to add the form before you changed it and then add a commit with your changes to see what is new
</blockquote></details>

Very sensible! I shall do just that next time 
___
*[forms/0202 AutoBookingInArrays, line 15 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md2-YGt1tRFNMvoQdEH:-MdvXQQT07s8X8f8AWXZ:b-dohcx4) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L15)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

Will do!
</blockquote></details>

All changed, ready for go llive


<!-- Sent from Reviewable.io -->

2021-07-06 13:45 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 108 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MdvwaMf3G7Riltq9g5-:-MdvwaMg2J8SPBcZMV2C:b-384k0b) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L108)):*
> ```Python
>     '''
>     # Define global variable for use in this function 
>     global patient_error
> ```

I'm not sure we need to put global here , especially if it's done above. TBH I don't know if global variables as used here are different to what I usually go but I think it might not be needed.

If an error is created/caught in a function we could create a local variable to record if a error is present or not (as per line 131 - holding true or false) and just return that variable. This variable should be created at the start of the function with a default value, eg assuming all is ok and then it will only be changed if there is an issue, or vice versa.

Then, when the function is called you could capture the error and use it elsewhere
eg patient_error=import_check_patients_table_moka(df_row) and update the dataframe accordingly
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 277 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mdw113cCqzv1hzLSQSl:-Mdw113cCqzv1hzLSQSm:bemw6ap) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L277)):*
> ```Python
>     '''
>     # Define global variable for use in this function 
>     global test_error
> ```

as above not sure what it should be a global variable here. I think a local variable which is returned is fine. That way we make sure that variable is reset each time the function is called.
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 437 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mdw2x0S2eDCYfzKFWdI:-Mdw2x0S2eDCYfzKFWdJ:b-9chp70) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L437)):*
> ```Python
>     # Define global variable for use in this function 
>     global error_occurred
>     # Count for number of samples which have errors & how many have passed 
> ```

as above


<!-- Sent from Reviewable.io -->

2021-07-06 14:11 UTC, ErinPeat reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @aledj2 and @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 108 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MdvwaMf3G7Riltq9g5-:-Mdw8O82A-iX7YHVgdu7:b-5ngxdt) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L108)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

I'm not sure we need to put global here , especially if it's done above. TBH I don't know if global variables as used here are different to what I usually go but I think it might not be needed.

If an error is created/caught in a function we could create a local variable to record if a error is present or not (as per line 131 - holding true or false) and just return that variable. This variable should be created at the start of the function with a default value, eg assuming all is ok and then it will only be changed if there is an issue, or vice versa.

Then, when the function is called you could capture the error and use it elsewhere
eg patient_error=import_check_patients_table_moka(df_row) and update the dataframe accordingly
</blockquote></details>

Updated and changed 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 277 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mdw113cCqzv1hzLSQSl:-Mdw8RW3BDoz97lu_6OV:b-5ngxdt) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L277)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above not sure what it should be a global variable here. I think a local variable which is returned is fine. That way we make sure that variable is reset each time the function is called.
</blockquote></details>

Updated and changed 
___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 437 at r4](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Mdw2x0S2eDCYfzKFWdI:-Mdw8nOC0y56vGok9WH0:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/e337c7515e9fb16f0f2836fe272ed2c70bbd66b0/code/automate_array_booking_in/ImportTxtToDB.py#L437)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above
</blockquote></details>

Done.
___
*[forms/0202 AutoBookingInArrays, line 15 at r1](https://reviewable.io/reviews/moka-guys/moka-fe/670#-Md2-YGt1tRFNMvoQdEH:-Mdw8lesAf4yZ8lpLFgv:b-896fix) ([raw file](https://github.com/moka-guys/moka-fe/blob/3c9efa963421354b6b0d4f99ad097bbc00c7dd77/forms/0202 AutoBookingInArrays#L15)):*
<details><summary><i>Previously, ErinPeat (Erin Peat) wrote…</i></summary><blockquote>

All changed, ready for go llive
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-06 14:17 UTC, aledj2 requested changes
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 271 at r5](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MdwATcp6uQ3ALuV9s_u:-MdwATcp6uQ3ALuV9s_v:b-kk03fb) ([raw file](https://github.com/moka-guys/moka-fe/blob/9022feb1ec90193656290e756cabb4715116e7f1/code/automate_array_booking_in/ImportTxtToDB.py#L271)):*
> ```Python
> 
>     INPUT: The index of the current row of the df that is being looped through by the script 
>     RETURN: None
> ```

sorry!


<!-- Sent from Reviewable.io -->

2021-07-06 14:24 UTC, ErinPeat reviewed
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @ErinPeat)

___
*[code/automate_array_booking_in/ImportTxtToDB.py, line 271 at r5](https://reviewable.io/reviews/moka-guys/moka-fe/670#-MdwATcp6uQ3ALuV9s_u:-MdwC71lAuPWOBxceBQe:b-qajv6q) ([raw file](https://github.com/moka-guys/moka-fe/blob/9022feb1ec90193656290e756cabb4715116e7f1/code/automate_array_booking_in/ImportTxtToDB.py#L271)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

sorry!
</blockquote></details>

ARGH, I'm sorry! Done 


<!-- Sent from Reviewable.io -->

2021-07-06 14:25 UTC, aledj2 approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/moka-fe/670)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ErinPeat)



<!-- Sent from Reviewable.io -->

2021-07-06 14:25 UTC, merged